method: bayes
metric:
  goal: minimize
  name: validation/loss
parameters:
  batch_size:
    values:
      - 32
  device:
    value: cuda
  dropout_rate:
    distribution: uniform
    max: 0.5
    min: 0.1
  epochs:
    distribution: int_uniform
    max: 200
    min: 50
  log:
    value: true
  log_steps:
    values:
      - 10
  lr:
    distribution: uniform
    max: 0.01
    min: 0.0001
  momentum:
    distribution: uniform
    max: 0.99
    min: 0.5
  num_workers:
    value: 10
  remote_path:
    value: true
  seed:
    values:
      - 42
      - 123
      - 456
      - 789
  val_steps:
    values:
      - 1
program: train.py